export const DISTRICT_LIST = 'DISTRICT_LIST';
export const SELECT_DISTRICT_FROM = 'SELECT_DISTRICT_FROM';
export const SELECT_DISTRICT_TO = 'SELECT_DISTRICT_TO';
export const SELECT_DATE = 'SELECT_DATE';
export const VIEW_SEATS = 'VIEW_SEATS';